services:
  spring-boot-app:
    image: spring-api:latest
    container_name: spring-boot-app
    restart: always
    depends_on:
      - MyDB
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/users_database?useSSL=false&allowPublicKeyRetrieval=true
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - spring-net


  MyDB:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_database
    ports:
      - "3306:3306"
    networks:
      - spring-net

networks:
  spring-net:

      