apiVersion : apps/v1
kind : Deployment
metadata :
  name : spring-boot-app
  namespace : springboot
spec :
  replicas : 2
  selector :
    matchLabels : 
      app : spring-boot-app
  template :
    metadata :
      labels :
        app : spring-boot-app
    spec :
      containers :
        - name : spring-boot-app
          image : spring-boot-rest-api:latest    
          imagePullPolicy : IfNotPresent
          ports :
            - containerPort : 8081
          env:
              - name: SPRING_DATASOURCE_URL
                value: jdbc:mysql://mysql-db:3306/users_database?useSSL=false&allowPublicKeyRetrieval=true
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: MYSQL_USER
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: MYSQL_PASSWORD
