apiVersion : v1
kind : Service
metadata :
  name : spring-boot-service
  namespace : springboot
spec :
  selector : 
    app : spring-boot-app
  type : NodePort
  ports :
    - port: 8081
      targetPort: 8081
      nodePort: 30081